export { default as Day1 } from './day1/day1'
export { default as Day2 } from './day2/day2'
export { default as Day3 } from './day3/day3'
export { Day4 } from './day4/day4'
export { Day5 } from './day5/day5'
export { default as Day6 } from './day6/day6'
export { default as Day7 } from './day7/day7'
export { default as Day8 } from './day8/day8'